### PR TITLE
first crack at a docs page by organizing readme into sections

### PR DESCRIPTION
**Pull request by ducks**

### CODE REVIEW

**Comment by LucioFranco** [comment]
@ducks this is awesome. I don't have much time today to review it but this is awesome!

**Comment by ducks** [comment]
Thanks :)

It's been fun to work on.

Have a couple rough ideas of a sidebar menu and just going to post a screenshot so anyone can have a quick peek of it.

Lemme know what y'all think.

screen shot 2016-11-13 at 2 59 50 pm
screen shot 2016-11-13 at 3 00 00 pm

**Comment by ducks** [comment]
One thing to note is none of the liquid examples are printing. I'm guessing we'll just need to escape into html codes but just haven't done that yet.

**Comment by johannhof** [comment]
@ducks can you rebase this? :)

We need to come up with a plan for styling the top level navigation. I kinda liked the idea of these having the same color as the pages they're navigating to. We could also try to color them in the logo colors, although that might also look weird. :D

Mmh I like both side navigation styles really. Maybe the grey one a bit more :)

**Comment by ducks** [comment]
Rebased. 

And that's not a bad idea, re nav item color for each pages body bg. I could throw that in another PR. Can add another that uses the grey/orange tab too instead of orange.

**Comment by johannhof** [comment]
Alright thanks, I'll merge this for now, it's all a bit WIP anyway :)

**Pull request merged**
