### PR TITLE
Rectangle menu style idea

### PR DESCRIPTION
**Pull request by johannhof**
Turns the menu into these triangular rectangle thingies inspired by the logo. Currently looks like this:

screen shot 2016-11-08 at 11 24 08

Opinions? :)

### CODE REVIEW

**Comment by rjgoldsborough** [comment]
Those look slick. I tried to pull this down to look at mobile sizes and it seems to slightly break unless I put the flex back on nav after the breakpoint. `flex: 0` seems to make it go down the page a bit.


screen shot 2016-11-08 at 8 20 38 am
screen shot 2016-11-08 at 8 20 48 am

**Comment by johannhof** [comment]
@rjgoldsborough what do you mean by "slightly break" on mobile? were you able to resolve it?

**Comment by rjgoldsborough** [comment]
Sorry, I think that way I said that was confusing.
I was pulling it down to look at mobile, but then noticed what's in the screenshots.

`header nav` currently has a flex:0 on larger sizes which seems to break it down a line.
For me removing the flex: 0 fixes it but not even sure if you're seeing this.

**Comment by johannhof** [comment]
Ah I see, good catch! I'll remove the `flex:0`.

**Comment by rjgoldsborough** [comment]
Other than that, 👍

**Comment by johannhof** [comment]
Ok let's merge this and iterate from there

**Pull request merged**
